export const SEARCH_DATA = "SEARCH_DATA"
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
export const SET_FAVOURITES = "SET_FAVOURITES"
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE"
export const REMOVE_TO_FAVOURITE = "REMOVE_TO_FAVOURITE"